server:
  shutdown: graceful
  port: 1111

logging:
  file:
    name: ./logs/pacs-server.log
  logback:
    rolling-policy:
      file-name-pattern: ${LOG_FILE}-%d{yyyyMMdd}-%i.log
      max-file-size: 10MB
      max-history: 30
  level:
    root: info

pacs:
  aet: pacs-server
  bind-address: 0.0.0.0
  port: 1112

spring:
  servlet:
    multipart:
      location: ./tmp
      max-file-size: 200MB
      max-request-size: 2048MB